# Generated by Django 4.0.8 on 2023-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(max_length=255, null=True, upload_to='Pictures/%Y/%m/')),
            ],
        ),
    ]
