# Generated by Django 4.0.8 on 2024-04-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cracker', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Name', models.TextField(blank=True, default='')),
                ('customer_Address', models.TextField(blank=True, default='')),
                ('customer_PhoneNumber', models.TextField(blank=True, default='')),
                ('final_Bill_Amount', models.TextField(blank=True, default='')),
                ('customer_Email', models.TextField(blank=True, default='')),
                ('template', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cracker.template')),
            ],
        ),
    ]
