# Generated by Django 5.0.6 on 2024-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracker', '0005_billing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Rating', models.IntegerField()),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
