# Generated by Django 4.0.8 on 2023-05-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_no',
            field=models.TextField(blank=True, default=''),
        ),
    ]
